name: 'Commit build artefacts'
description: 'Commit build artefacts to a build repository'
author: 'mutoco'
branding:
  icon: copy
  color: purple
inputs:
  source:
    description: 'Source folder, defaults to ./build'
    required: false
    default: 'build'
  suffix:
    description: 'Build repository suffix, defaults to `-build`'
    required: false
    default: '-build'
  organisation:
    description: 'Will create repository for that organisation if set'
    required: false
  committer_email:
    description: 'Committer email'
    required: false
  committer_name:
    description: 'Committer name'
    required: false
    default: 'Anonymous'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}
